name: NoPhantoms
main: com.Melvin3000.NoPhantoms.NoPhantoms
version: 2.0
api-version: 1.15
folia-supported: true
commands:
    phantoms:
        description: Toggle if phantoms spawn for you
        usage: /<command>